---
title: STA5092Z 2026 Assignment 1
author:
  - name: Şebnem Er
    email: sebnem.er@uct.ac.za
    affiliations: 
        - id: uct
          name: University of Cape Town
          department: Statistical Sciences Department
          address: Rondebosch
          city: Cape Town
          state: Western Cape
          postal-code: 7701
abstract: | 
   In this assignment....
keywords: 
  - pied babbler
date: last-modified
bibliography: eda.bib
format:
  pdf:
    standalone: true
    toc: true
    number-sections: true
    engine: xelatex
    text: |
        \usepackage{lmodern}
        \usepackage[T1]{fontenc}
        \usepackage{amsmath}
        \usepackage{bm}
    keep-tex: true
    journal:
      name: Journal Name
      cite-style: authoryear
execute: 
  cache: true
---

```{r libraries_data}
#| echo: FALSE
#| warning: FALSE
#| eval: TRUE
#| message: FALSE
#| include: FALSE

library(ggplot2)
library(tidyr)
library(tidyverse)
library(dplyr)
library(gridExtra)
library(knitr)
library(kableExtra)

N <- 67
```

# Introduction

assignment

# Part 1 
Outliers [@xie2015]. assignment

Next section details ....

## Data Preparation

```{r}
#| echo: FALSE
#| warning: FALSE
#| eval: TRUE
#| message: FALSE
#| include: FALSE

y = c(1:5)
y
```

See the difference:

```{r}
#| echo: FALSE
#| warning: FALSE
#| eval: TRUE
#| message: FALSE
#| include: TRUE

y = c(1:5)
y
```

# References {.unnumbered}
